openapi: 3.1.3
info:
  title: 英雄資訊網
  summary: 各格英雄資訊的查詢API
  version: 0.0.1
paths:
  /heroes:
    get:
      summary: 多筆英雄基本資料
      description: 取得多筆的英雄基本資料
      parameters:
        - $ref: '#/components/parameters/NameHeader'
        - $ref: '#/components/parameters/PasswordHeader'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HeroInfo'
  /heroes/{heroId}:
    get:
      summary: 英雄的基本資料
      description: 取得英雄的基本資料
      parameters:
        - $ref: '#/components/parameters/NameHeader'
        - $ref: '#/components/parameters/PasswordHeader'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeroInfo'
components:
  # 以下schemas和rest後台的schemas大致相同——兩者實際上可以直接匯入
  # 共用的schema來使用，會省時間也會減少誤值的可能性(也就是說，這樣做會比較DRY)。
  # 為了去耦合性，這邊選擇重新定義相關的schema，避免以後上游資料來源的格式變了，
  # 造成下游的api也得跟著改變，同時也保留著下游資料格式的定義權。
  schemas:
    HeroInfo:
      title: Hero Info
      type: object
      properties:
        id:
          type: string
          description: 英雄的ID
        name:
          type: string
          description: 名字
        image:
          type: string
          format: uri
          description: 大頭照的連結
        profile:
          $ref: '#/components/schemas/HeroStats'
          description: 基本能力值。請求需要帶有效的驗證標頭，伺服器才會回傳此欄位。
      additionalProperties: false
      required:
        - id
        - name
        - image
      examples: 
        - id: "1"
          name: Daredevil
          image: http://i.annihil.us/u/prod/marvel/i/mg/6/90/537ba6d49472b/standard_xlarge.jpg
        - id: "1"
          name: Daredevil
          image: http://i.annihil.us/u/prod/marvel/i/mg/6/90/537ba6d49472b/standard_xlarge.jpg
          profile:
            str: 2
            int: 7
            agi: 9
            luk: 7
    HeroStats:
      title: Hero Stats
      type: object
      properties:
        str:
          type: number
          description: 力量值
        int:
          type: number
          description: 智力值
        agi:
          type: number
          description: 敏捷值
        luk:
          type: number
          description: 運氣值
      additionalProperties: false
      required:
        - str
        - int
        - agi
        - luk
      example:
        str: 2
        int: 7
        agi: 9
        luk: 7
  parameters:
    NameHeader:
      name: Name
      in: header
      schema:
        type: string
      description: 用戶名稱。用於驗證詳細資料請求。
    PasswordHeader:
      name: Password
      in: header
      schema:
        type: string
      description: 用戶密碼。用於驗證詳細資料請求。
externalDocs:
  url: https://github.com/qwwqe/heroes/blob/main/README.md
  description: 英雄資訊網的git repo